// Package common provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package common

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// BaseSuccessResponse defines model for BaseSuccessResponse.
type BaseSuccessResponse struct {
	Message    string `json:"message"`
	StatusCode int    `json:"status_code"`
}

// StandardErrorResponse defines model for StandardErrorResponse.
type StandardErrorResponse struct {
	Details   *string                 `json:"details,omitempty"`
	Errors    *map[string]interface{} `json:"errors,omitempty"`
	Instance  *string                 `json:"instance,omitempty"`
	Status    *int                    `json:"status,omitempty"`
	Timestamp *string                 `json:"timestamp,omitempty"`
	Title     *string                 `json:"title,omitempty"`
	TraceId   *string                 `json:"trace_id,omitempty"`
	Type      *string                 `json:"type,omitempty"`
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/3yPwUoEMQyG3yXnPsEcBe/iHkWW2MbdyDSpSeYgS99dpqKsbPVW8vX78+cCWWtTIQmH",
	"5QKez1RxPO/Q6bDlTO6P5E3FaR8300YWTONTJXc8DRAfjWABD2M5QU/ggbH5MWu55ixBJzLoPYHR+8ZG",
	"BZann6Tf3nP69vTljXLsuYdAKWjl3kzt72qFAnn1aTXa1YGwFA5WwfXh2u6TvSweKPm/Y2d3Jgiu5IG1",
	"Tc3gWOeZYZjpyGUOx+AG3Bbvo/qrwiLbuibQRoKNYQFI0DDO/kX6ZwAAAP//4Rq8vwwCAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
