// Package order provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package order

// Order defines model for Order.
type Order struct {
	Amount float32 `json:"amount"`
	Id     string  `json:"id"`
	UserId string  `json:"userId"`
}
