openapi: 3.0.0
info:
  title: Order Domain API
  version: 1.0.0
servers:
  - url: /api/v1 #specify route group prefix here (only in v3+)
paths:
  /order:
    get:
      summary: Get all orders
      responses:
        '200':
          description: A list of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        amount:
          type: number
      required:
        - id
        - userId
        - amount