openapi: 3.0.0
info:
  title: User Domain API
  version: 1.0.0
servers:
  - url: /api/v1 #specify route group prefix here (only in v3+)
paths:
  /user:
    get:
      summary: Get users with filters
      security:
        - bearerAuth: []
      parameters:
        - name: email
          in: query
          description: email to filter by
          required: false
          style: form
          schema:
            type: string
        - name: is_active
          in: query
          description: is_active to filter by
          required: false
          style: form
          schema:
            type: string
        - name: page
          in: query
          description: filter by page
          required: false
          schema:
            type: integer
            default: 1
            format: int64
            nullable: false
        - name: pageSize
          in: query
          description: size of each page
          required: false
          schema:
            type: integer
            default: 10
            format: int64
            nullable: false
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserResponse'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '../common/response.yaml#/components/schemas/StandardErrorResponse'
        '500':
          description: internal error
          content:
            application/json:
              schema:
                $ref: '../common/response.yaml#/components/schemas/StandardErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-oapi-codegen-extra-tags:
            db: id
        email:
          type: string
          x-oapi-codegen-extra-tags:
            db: email
        first_name:
          type: string
          x-oapi-codegen-extra-tags:
            db: first_name
        last_name:
          type: string
          x-oapi-codegen-extra-tags:
            db: last_name
        is_active:
          type: integer
          format: int32
          x-oapi-codegen-extra-tags:
            db: is_active
    PaginatedUserResponse:
      type: object
      properties:
        data:
          type: array
          items :
            $ref: "#/components/schemas/User"
        pagination:
          type: object
          properties:
            currentPage:
              type: integer
              format: int64
            pageSize:
              type: integer
              format: int64
            totalItems:
              type: integer
              format: int64
            totalPages:
              type: integer
              format: int64
        filters:
          type: object
          x-go-type: interface{}
          description: show applied filters parameter
          
          
    