// Package user provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package user

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateUserRequestRole.
const (
	Admin  CreateUserRequestRole = "admin"
	Member CreateUserRequestRole = "member"
)

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	Age      *int                  `json:"age,omitempty"`
	Email    openapi_types.Email   `json:"email"`
	Role     CreateUserRequestRole `json:"role"`
	Username string                `json:"username"`
}

// CreateUserRequestRole defines model for CreateUserRequest.Role.
type CreateUserRequestRole string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorCode *string `json:"error_code,omitempty"`
	Message   *string `json:"message,omitempty"`
}

// User defines model for User.
type User struct {
	Age      *int    `json:"age,omitempty"`
	Email    *string `json:"email,omitempty"`
	Id       *int64  `json:"id,omitempty"`
	Role     *string `json:"role,omitempty"`
	Username *string `json:"username,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Role role to filter by
	Role *string `form:"role,omitempty" json:"role,omitempty"`

	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest
